version: '3.7'

services:
  dbpostgres:
    build: 
      context: ./postgres
    volumes: 
      - ${DOCKER_POSTGRES_CUSTOM_MOUNT}:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: twittercannon
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # network_mode: host
